// sfx/list.js
// This file contains a list of audio files used in the application.
// Each audio file is represented as an object with properties such as file path, name, class, and loop status.
// The audio files are organized into categories for better management and accessibility.
// The audio files are stored in a directory named 'sfx'.
// This script is used to fetch and display audio files in the application.
// The audio files are categorized into speech, default sounds, and FM radio sounds.
// The audio files can be played, paused, and looped based on user interaction.
// The audio files are loaded dynamically from the specified directory and displayed in the UI.

// LEGEND TO ADD THE AUDIO FILES

// Each audio file is an object with the following properties:
// - file: The path to the audio file relative to the 'sfx' directory.
// - name: The display name for the audio file, which can include HTML formatting.
// - class: The CSS class to apply for styling purposes.
// - loop: A boolean indicating whether the audio file should loop when played.

// class by different categories

// category_speech: Speech and Meme Sounds
// category_default: Default sound effects
// category_fm: FM Radio Sounds
// category_sfx: Sound Effects
// category_music: Music and Jingles
// category_fm: FM Radio Sounds

// if not specified, it will be categorized as 'category_default'

// Directory containing your audio files
const audioDir = 'sfx';

// List of audio files (add more as needed)
const audioList = [
    { file: 'default/bicolbabaero.mp3', name: '<b>record_voice_over</b><br>Basta Bicolano', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'default/siramsana.mp3', name: '<b>record_voice_over</b><br>Siram Sana!', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'default/gwapoangsound.mp3', name: '<b>record_voice_over</b><br>Gwapo ang Sound<br><h5>Wala nobya!</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack4/gwapoangsound-gutomna.mp3', name: '<b>record_voice_over</b><br>Gwapo ang Sound<br><h5>Gutom na!</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'default/dimanakogwapo.mp3', name: '<b>record_voice_over</b><br>Di Manako Gwapo', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'default/nindotangtukar.mp3', name: '<b>record_voice_over</b><br>Nindot ang Tukar', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'default/sayawta.m4a', name: '<b>record_voice_over</b><br>Sayaw Ta Lupig Sila!', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack2/holdonholiday.mp3', name: '<b>record_voice_over</b><br>Hold on Holiday', class: 'category_speech', loop: false, isOffensive: true },
    { file: 'sfx-pack3/emotional-damage.mp3', name: '<b>record_voice_over</b><br>Emotional Damage', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack2/nuclear-bombs.mp3', name: '<b>record_voice_over</b><br>Nuclear Bombs', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack3/ayawkolbatapakokol.mp3', name: '<b>record_voice_over</b><br>Ayaw Kol, Bata pa ko Kol!', class: 'category_speech', loop: false, isOffensive: true },
    { file: 'rldavid/ayawkol.mp3', name: '<b>record_voice_over</b><br>Ayaw Kol!<br><h5>[RL] David</h5>', class: 'category_speech', loop: false, isOffensive: true },
    { file: 'meme/meme-ayawkol.mp3', name: '<b>record_voice_over</b><br>Ayaw Kol!<br><h5>Pandesal Rolling Store</h5>', class: 'category_speech', loop: false, isOffensive: true },
    { file: 'meme/meme-baliklamu.mp3', name: '<b>record_voice_over</b><br>Balik Lamu!<br><h5>Pandesal Rolling Store</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'default/hindilahat.m4a', name: '<b>record_voice_over</b><br>Hindi Lahat ng Gwapo', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack4/hindilahat2.mp3', name: '<b>record_voice_over</b><br>Hindi Lahat ng Gwapo 2', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'default/robotsound1.mp3', name: '<b>record_voice_over</b><br>Robot Sound Colossous', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'default/robotsound2.mp3', name: '<b>record_voice_over</b><br>Robot Sound Robotoid', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack4/ay-kalamii.mp3', name: '<b>record_voice_over</b><br>AY! Ka Lamii!', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack4/ginagawamo.mp3', name: '<b>record_voice_over</b><br>Ginagawa Mo!', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack4/ginagawamo-short.mp3', name: '<b>record_voice_over</b><br>Ginagawa Mo! Short', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack4/hanap.mp3', name: '<b>record_voice_over</b><br>Hanap!', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack4/magmahal.mp3', name: '<b>record_voice_over</b><br>Magmahal', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfx-pack3/momentslater.mp3', name: '<b>record_voice_over</b><br>A Few Moments Later', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-3aug2025/sana-all.mp3', name: '<b>record_voice_over</b><br>Sana All!', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'meme/rldavid-sanaall.mp3', name: '<b>record_voice_over</b><br>Sana All!<br><h5>[RL] David</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'rldavid/sanaall2.mp3', name: '<b>record_voice_over</b><br>Sana All! 2<br><h5>[RL] David</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'meme/meme-sanaall.mp3', name: '<b>record_voice_over</b><br>Sana All!<br><h5>Pandesal Rolling Store</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-3aug2025/uyuy-sanaall.mp3', name: '<b>record_voice_over</b><br>Uy Uy, Sana All!', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-3aug2025/wow-sanaall.mp3', name: '<b>record_voice_over</b><br>Wow! Sana All!', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'meme/meme-papakdul.mp3', name: '<b>record_voice_over</b><br>Papak Dul!<br><h5>Pandesal Rolling Store</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'rldavid/deloraxpower.mp3', name: '<b>record_voice_over</b><br>DeLora X Power<br><h5>[RL] David</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'rldavid/clotdelora.mp3', name: '<b>record_voice_over</b><br>Clot DeLora<br><h5>[RL] David</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'meme/sorryna.mp3', name: '<b>record_voice_over</b><br>Sorry na, Wag kana galit UwU</h5>', class: 'category_speech', loop: false, isOffensive: false },
    { file: 'laughs/ayayhaha.mp3', name: '<b>sentiment_excited</b><br>Ayay! Haha', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahafun.mp3', name: '<b>sentiment_excited</b><br>Haha Fun', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahaha.mp3', name: '<b>sentiment_excited</b><br>Hahaha', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahaind.mp3', name: '<b>sentiment_excited</b><br>Haha India', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahaha2.mp3', name: '<b>sentiment_excited</b><br>Hahaha 2', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahaha3.mp3', name: '<b>sentiment_excited</b><br>Hahaha 3', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahaha4.mp3', name: '<b>sentiment_excited</b><br>Hahaha 4', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahaha5.mp3', name: '<b>sentiment_excited</b><br>Hahaha 5', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahaha6.mp3', name: '<b>sentiment_excited</b><br>Hahaha 6', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahaha7.mp3', name: '<b>sentiment_excited</b><br>Hahaha 7', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/hahaha8.mp3', name: '<b>sentiment_excited</b><br>Hahaha 8', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/childlaugh.mp3', name: '<b>sentiment_excited</b><br>Child Laugh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/everyonelaugh.mp3', name: '<b>sentiment_excited</b><br>Everyone Laugh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/sillylaugh.mp3', name: '<b>sentiment_excited</b><br>Silly Laugh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/atumalaca.mp3', name: '<b>sentiment_excited</b><br>Atumalaca Laugh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/oh-no-no-no-no-laugh.mp3', name: '<b>sentiment_excited</b><br>Oh, No 4x Laugh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/ngakak-laugh-annoying.mp3', name: '<b>sentiment_excited</b><br>Ngakak Laugh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/singh-haha.mp3', name: '<b>sentiment_excited</b><br>Singh Laugh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/og-eatbulaga-laugh.mp3', name: '<b>sentiment_excited</b><br>Eat Bulaga! Laugh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/og-eatbulaga-laugh-short.mp3', name: '<b>sentiment_excited</b><br>Eat Bulaga! Laugh Short', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/og-ebkid-laugh.mp3', name: '<b>sentiment_excited</b><br>Eat Bulaga! Kid Laugh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'laughs/og-ebkid-laugh-short.mp3', name: '<b>sentiment_excited</b><br>Eat Bulaga! Kid Laugh Short', class: 'category_default', loop: false, isOffensive: false },

    { file: 'default/airhorn.mp3', name: '<b>campaign</b><br>Airhorn', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/airhorn-loop.mp3', name: '<b>campaign</b><br>Airhorn Loop', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack4/bushorn.mp3', name: '<b>campaign</b><br>Bus Horn', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack4/bushorn-loop.mp3', name: '<b>campaign</b><br>Bus Horn Loop', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-4aug2025/beephorn.mp3', name: '<b>campaign</b><br>Beep Horn', class: 'category_default', loop: false, isOffensive: false },

    { file: 'applauses/appaluse.mp3', name: '<b>cheer</b><br>Appluases', class: 'category_default', loop: false, isOffensive: false },
    { file: 'applauses/appaluses1.mp3', name: '<b>cheer</b><br>Appluases A', class: 'category_default', loop: false, isOffensive: false },
    { file: 'applauses/appaluses2.mp3', name: '<b>cheer</b><br>Appluases B', class: 'category_default', loop: false, isOffensive: false },
    { file: 'applauses/appaluses3.mp3', name: '<b>cheer</b><br>Appluases C', class: 'category_default', loop: false, isOffensive: false },
    { file: 'applauses/appaluses4.mp3', name: '<b>cheer</b><br>Appluases D', class: 'category_default', loop: false, isOffensive: false },

    { file: 'giftscore/gift.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift', class: 'category_default', loop: false, isOffensive: false },
    { file: 'giftscore/gift-drum.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift - Drum', class: 'category_default', loop: false, isOffensive: false },
    { file: 'giftscore/gift-drumbass.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift - Drum & Bass', class: 'category_default', loop: false, isOffensive: false },
    { file: 'giftscore/gift-goodjob.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift - Good Job!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'giftscore/gift-verygood.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift - Very Good!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'giftscore/gift-ygi.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift - You Got it!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'giftscore/gift-gwilling.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift - God Willing', class: 'category_default', loop: false, isOffensive: false },
    { file: 'giftscore/gift-niceone.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift - Nice One', class: 'category_default', loop: false, isOffensive: false },
    { file: 'giftscore/gift-nicejob.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift - Nice Job', class: 'category_default', loop: false, isOffensive: false },
    { file: 'giftscore/gift-almostthere.mp3', name: '<b>featured_seasonal_and_gifts</b><br>Gift - Almost there!', class: 'category_default', loop: false, isOffensive: false },

    { file: 'default/ahyeah.mp3', name: 'Ah Yeah', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/aww.mp3', name: 'Aww', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/buueng.mp3', name: 'Buueng', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/cherring.mp3', name: 'Cheering', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/cow.mp3', name: 'Cow', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/ding.mp3', name: 'Ding', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/doorbell.mp3', name: 'Doorbell', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/doorbell2.mp3', name: 'Doorbell 2', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/drumrolllong.mp3', name: 'Drumroll Long', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/drumrollmed.mp3', name: 'Drumroll Medium', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/drumrollshort.mp3', name: 'Drumroll Short', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/ehem.mp3', name: 'Ehem', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/failsax.m4a', name: 'Fail Sax', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/fail.mp3', name: 'Fail', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/failure.mp3', name: 'Failure', class: 'category_default', loop: false, isOffensive: false },
    
    { file: 'default/gotcha.m4a', name: 'Gotcha', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/healed.mp3', name: 'Healed', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/highscore.mp3', name: 'Highscore', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/item.m4a', name: 'Item', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/iyeah.mp3', name: 'Iyeah', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/joinave-lvu1.mp3', name: '<b>check_circle</b><br>Join Avenue LV1', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/joinave-lvu2.mp3', name: '<b>check_circle</b><br>Join Avenue LV2', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/losing.mp3', name: 'Losing', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/marcha.mp3', name: 'Marcha', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/notify.mp3', name: 'Notify', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/ohno.mp3', name: 'Oh No!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/outofmyway.mp3', name: 'Out of My Way', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/sad.mp3', name: 'Sad', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/sadtrombone.mp3', name: 'Sad Trombone', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/scratch.mp3', name: 'Scratch', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/special.m4a', name: 'Special', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/surprise.mp3', name: 'Surprise', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/tadada.mp3', name: 'Tadada', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/taw.mp3', name: 'Taw', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/toinks.mp3', name: 'Toinks!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/uwu!.mp3', name: 'Uwu!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/warn.mp3', name: 'Warn', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/welldone.mp3', name: 'Well Done', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/wow.mp3', name: 'Wow', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/yahoo.mp3', name: 'Yahoo', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/yeeha.mp3', name: 'Yeeha', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack4/yeeho.mp3', name: 'Yehoo', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack4/yipee.mp3', name: 'Yipee', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack2/awsheet.mp3', name: 'Aw SH*T!', class: 'category_default', loop: false, isOffensive: true },
    { file: 'sfx-pack2/dj-rewind-sound.mp3', name: 'Rewind', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack2/record-dj-scratch.mp3', name: 'Scratch 2', class: 'category_default', loop: false, isOffensive: false },

    { file: 'sfx-pack2/tapiboong.mp3', name: 'Tapi Boong', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack2/weeehahaha.mp3', name: 'Weeeee!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/impact.wav', name: 'Impact 01', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack3/ding2.mp3', name: 'Ding 2', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack3/dundundun.mp3', name: 'Dun Dun Dun', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack3/nothing-beats-a-jet2-holiday.mp3', name: 'Jet2 Holiday', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack3/wronganswer.mp3', name: 'Wrong Answer!', class: 'category_default', loop: false, isOffensive: false },

    { file: 'msoffice-sounds/APPLAUSE2.WAV', name: 'Applause 2', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/ARROW.WAV', name: 'Arrow', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/BOMB.WAV', name: 'Bomb', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/BREEZE.WAV', name: 'Breeze', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/CAMERA.WAV', name: 'Camera', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/CASHREG.WAV', name: 'Cashreg', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/CHIMES.WAV', name: 'Chimes', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/CLICK.WAV', name: 'Click', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/COIN.WAV', name: 'Coin', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/DRUMROLL.WAV', name: 'Drumroll', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/EXPLODE.WAV', name: 'Explode', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/HAMMER.WAV', name: 'Hammer', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/LASER.WAV', name: 'Laser', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/PUSH.WAV', name: 'Push', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/SUCTION.WAV', name: 'Suction', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/TYPE.WAV', name: 'Type', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/VOLTAGE.WAV', name: 'Voltage', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/WHOOSH.WAV', name: 'Whoosh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'msoffice-sounds/WIND.WAV', name: 'Wind', class: 'category_default', loop: false, isOffensive: false },

    { file: 'sfx-pack3/shocked.mp3', name: 'Shocked', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack3/spongebob-fail.mp3', name: 'Spongebob Fail', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack3/uy.mp3', name: 'UY!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'default/screamdj.mp3', name: 'Scream DJ', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack4/bounce.mp3', name: 'Bounce', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack4/breakglass.mp3', name: 'Break Glass', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack4/buaing.mp3', name: 'Buaing!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack4/buing.mp3', name: 'Buing!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfx-pack4/huh.mp3', name: 'Huh?', class: 'category_default', loop: false, isOffensive: false },

    { file: 'sfxpack-cumulative-3aug2025/among-us-role-reveal-sound.mp3', name: 'Among Us Role Reveal', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-3aug2025/huh_37bAoRo.mp3', name: 'Asian HUH?', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-3aug2025/mac-quack.mp3', name: 'Mac Quack!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-3aug2025/metal-pipe-clang.mp3', name: 'Metal Pipe Clang', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-3aug2025/omgwow.mp3', name: 'Oh my God, Wow!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-3aug2025/tuco-get-out.mp3', name: 'Get out!', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-3aug2025/vine-boom.mp3', name: 'Vine Boom!', class: 'category_default', loop: false, isOffensive: false },

    { file: 'sfxpack-cumulative-4aug2025/clang2.mp3', name: 'Clang', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-4aug2025/failure-ohh.mp3', name: 'Failure Ohh', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-4aug2025/firework.mp3', name: 'Firework', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-4aug2025/kotomagic.mp3', name: 'Koto Magic', class: 'category_default', loop: false, isOffensive: false },

    { file: 'sfxpack-cumulative-4aug2025/transformate.mp3', name: 'Transformate', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-4aug2025/transformate2.mp3', name: 'Transformate 2', class: 'category_default', loop: false, isOffensive: false },
    { file: 'sfxpack-cumulative-4aug2025/transformate3.mp3', name: 'Transformate 3', class: 'category_default', loop: false, isOffensive: false },

    { file: 'fmtapers/startingevent.mp3', name: '<b>voicemail</b><br>Starting Event', class: 'category_fm', loop: false, isOffensive: false },
    { file: 'fmtapers/jingle.mp3', name: '<b>voicemail</b><br>Jingle', class: 'category_fm', loop: false, isOffensive: false },
    { file: 'fmtapers/urlistening.mp3', name: '<b>voicemail_2</b><br>You are Listening', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM
    { file: 'fmtapers/letsgotothemusic.mp3', name: '<b>voicemail_2</b><br>Lets Go To The Music', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM
    { file: 'fmtapers/vjdyfm.mp3', name: '<b>voicemail_2</b><br>FM Taper', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM
    { file: 'fmtapers/vjdyfm2.mp3', name: '<b>voicemail_2</b><br>FM Taper 2', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM
    { file: 'fmtapers/vjdyfmtaper.mp3', name: '<b>voicemail_2</b><br>FM Taper Full', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM
    { file: 'fmtapers/nowopen.m4a', name: '<b>voicemail_2</b><br>DJ Drop Now Open', class: 'category_fm', loop: false, isOffensive: false },
    { file: 'fmtapers/ovo-sound-radio.mp3', name: '<b>voicemail</b><br>OVO Sound Radio', class: 'category_fm', loop: false, isOffensive: false },
    { file: 'fmtapers/thesebeatsarehot.mp3', name: '<b>voicemail</b><br>These Beats are Hot!', class: 'category_fm', loop: false, isOffensive: false },
    { file: 'fmtapers/wethebest.mp3', name: '<b>voicemail</b><br>We the Best!', class: 'category_fm', loop: false, isOffensive: false },
    { file: 'fmtapers/vjdyfm-speech.mp3', name: '<b>voicemail</b><br>FM Speech<br><h5>[RL] David</h5>', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM
    { file: 'fmtapers/upnext/upnext-baraylihantime.mp3', name: '<b>fast_forward</b><br>Up Next<br><h5>Baraylihan Time!</h5>', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM
    { file: 'fmtapers/upnext/upnext-genz.mp3', name: '<b>fast_forward</b><br>Up Next<br><h5>Turugtugan GenZ!</h5>', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM
    { file: 'fmtapers/upnext/upnext-afternoon.mp3', name: '<b>fast_forward</b><br>Up Next<br><h5>Afternoon Tulog</h5>', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM
    { file: 'fmtapers/upnext/upnext-chacha.mp3', name: '<b>fast_forward</b><br>Up Next<br><h5>Cha-Cha sa Gabi!</h5>', class: 'category_fm', loop: false, isOffensive: false }, // For VJDY FM

    { file: 'scoresounds/kumyoung90.mp3', name: '<b>stars_2</b><br>Kumyoung Almost', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/kumyoung100.mp3', name: '<b>stars_2</b><br>Kumyoung Excellent!', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro1.mp3', name: '<b>stars_2</b><br>Megapro Fanfare A', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro2.mp3', name: '<b>stars_2</b><br>Megapro Fanfare B', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/videokescore.mp3', name: '<b>stars_2</b><br>Karaoke Score OG Ringtone', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/og-karaoke-70.mp3', name: '<b>stars_2</b><br>OG Karaoke 70', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/og-karaoke-80.mp3', name: '<b>stars_2</b><br>OG Karaoke 80', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/og-karaoke-90.mp3', name: '<b>stars_2</b><br>OG Karaoke 90', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/og-karaoke-100.mp3', name: '<b>stars_2</b><br>OG Karaoke 100', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/victory.mp3', name: '<b>stars_2</b><br>Victory', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/winmarch.m4a', name: '<b>stars_2</b><br>Lexing Win March', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare01.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 1', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare02.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 2', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare03.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 3', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare04.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 4', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare05.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 5', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare06.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 6', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare07.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 7', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare08.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 8', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare09.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 9', class: 'category_score', loop: false, isOffensive: false },
    { file: 'scoresounds/megapro/fanfare10.mp3', name: '<b>stars_2</b><br>MegaPro Fanfare 10', class: 'category_score', loop: false, isOffensive: false },
    
    { file: 'musicscore/abonemp3cut.mp3', name: '<b>music_note</b><br>Abone - Score', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/aybarbiesabikona.mp3', name: '<b>music_note</b><br>AY! Barbie Sabi ko na!', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/original_zeowgw1.mp3', name: '<b>music_note</b><br>Crab Rave', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/this-girl-kungs.mp3', name: '<b>music_note</b><br>This Girl', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/celebrate-dj-snake.mp3', name: '<b>music_note</b><br>Celebrate - DJ Snake', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/SEQ_BGM_PLEASUREBOAT.mp3', name: '<b>music_note</b><br>Royal Unova', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/track01.mp3', name: '<b>music_note</b><br>90s Retro', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/track02.mp3', name: '<b>music_note</b><br>Millennium', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/track03.mp3', name: '<b>music_note</b><br>Classic Retro', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/track04.mp3', name: '<b>music_note</b><br>Modern Retro', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/track05.mp3', name: '<b>music_note</b><br>Backmaps Original', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/track06.mp3', name: '<b>music_note</b><br>DOLA Lo-Fi', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/azalea-blackthrown.mp3', name: '<b>music_note</b><br>Azalea', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/viridian.mp3', name: '<b>music_note</b><br>Viridian', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/lavender.mp3', name: '<b>music_note</b><br>Lavender Town', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/hanada-marchcity.mp3', name: '<b>music_note</b><br>Hanada Pokemon', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/VJDYFMScore.mp3', name: '<b>music_note</b><br>VJDY FM Score', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/upsidedowncake.mp3', name: '<b>music_note</b><br>Upside Down Cake Sting', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/happyday.mp3', name: '<b>music_note</b><br>Happy Day Short', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/inspo2024.mp3', name: '<b>music_note</b><br>Inspiration 2024 Sting', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/retrodance-sting.wav', name: '<b>music_note</b><br>Retro Dance Sting', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/ogtrap1.mp3', name: '<b>music_note</b><br>OG Tarp', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/1-ice-cream.mp3', name: '<b>music_note</b><br>Ice Cream Yummy!', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/2-whisper.mp3', name: '<b>music_note</b><br>Careless Whisper', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/3-kinikilig.mp3', name: '<b>music_note</b><br>Kinikilig &#x1F495;', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/4-pasimpel.mp3', name: '<b>music_note</b><br>Pa-simple Comedy!', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/sad-meow-song.mp3', name: '<b>music_note</b><br>Meow, Meow!', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/oiia-blue.mp3', name: '<b>music_note</b><br>OIIA - blue yung kai', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/ngiti-mp3cut.mp3', name: '<b>music_note</b><br>Ngiti', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/pdr/achillintheair.mp3', name: '<b>music_note</b><br>A Chill in the Air', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/pdr/bendandstr.mp3', name: '<b>music_note</b><br>Bend & Stretch', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/pdr/capri.mp3', name: '<b>music_note</b><br>Capri Twist', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/pdr/carefree.mp3', name: '<b>music_note</b><br>Carefree', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/pdr/crisp.mp3', name: '<b>music_note</b><br>Crisp in the Afternoon', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/pdr/funnytune.mp3', name: '<b>music_note</b><br>Funny Tune', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/pdr/holicollect.mp3', name: '<b>music_note</b><br>Holiday Connection', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/pdr/jollyboat.mp3', name: '<b>music_note</b><br>Jollyboat', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/pdr/pdr-japansong.m4a', name: '<b>music_note</b><br>PDR Japan Song', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/ndsmiiedit.wav', name: '<b>music_note</b><br>Tomodachi DS Mii Editor', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/ndsmiihall.mp3', name: '<b>music_note</b><br>Tomodachi DS City Hall', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/topoftheworld.mp3', name: '<b>music_note</b><br>Top of the World', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/cinderella-tlakosayocover.mp3', name: '<b>music_note</b><br>TL Ako Sayo Cover Cue', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/kiligmaja.mp3', name: '<b>music_note</b><br>Kilig by <strong>Maja</strong>', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/kiligmaja-indo.mp3', name: '<b>music_note</b><br>Kilig - Indonesian Version', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/eva.mp3', name: '<b>music_note</b><br>Eva by <strong>Vintage</strong>', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/dancewithme.mp3', name: '<b>music_note</b><br>Dance with Me<br><em>Cue 2</em>', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/connection.wav', name: '<b>music_note</b><br>Nintendo Wi-Fi Connection', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/sequence/complexetron-drum.wav', name: '<b>music_note</b><br>Complexetron Drum', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/thisgirl-score/intro.wav', name: '<b>repeat</b><br>This Girl Intro', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/thisgirl-score/qa.wav', name: '<b>repeat</b><br>This Girl Q&A', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/thisgirl-score/score-bass.wav', name: '<b>repeat</b><br>This Girl Score - Bass Only', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/thisgirl-score/score.wav', name: '<b>repeat</b><br>This Girl Score', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/thisgirl-score/stage.wav', name: '<b>repeat</b><br>This Girl Stage', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/fil-chorus.wav', name: '<b>music_note</b><br>Falling in Love Cue Chorus', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/OMDLR.wav', name: '<b>music_note</b><br>OMDLR Cue Chorus', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/spinningseal/spinseal-1.m4a', name: '<b>music_note</b><br>Spinning Seal FM', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/spinningseal/spinseal-2.mp3', name: '<b>music_note</b><br>Spinning Seal FM Ringtone', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/complextreon.wav', name: '<b>music_note</b><br><strong>nucleon</strong><br>Complextreon', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/housework.wav', name: '<b>music_note</b><br><strong>nucleon</strong><br>Housework', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/steptime.wav', name: '<b>music_note</b><br><strong>nucleon</strong><br>Steptime', class: 'category_musicscore', loop: true, isOffensive: false },
    { file: 'musicscore/bass-asher.wav', name: '<b>music_note</b><br>Bass <strong>Asher Postman</strong>', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/house-asher.wav', name: '<b>music_note</b><br>House <strong>Asher Postman</strong>', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/wonderzoo.mp3', name: '<b>music_note</b><br>Wonderzoo by <strong>Gameloft</strong>', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/wonderzoointro.mp3', name: '<b>music_note</b><br>Wonderzoo Intro by <strong>Gameloft</strong>', class: 'category_musicscore', loop: false, isOffensive: false },
    { file: 'musicscore/wonderzoowin.mp3', name: '<b>music_note</b><br>Wonderzoo Win <strong>Gameloft</strong>', class: 'category_musicscore', loop: false, isOffensive: false },

    { file: 'default/vibraon.mp3', name: '<b>notification_sound</b><br>Airport Vibra On', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'default/vibraoff.mp3', name: '<b>notification_sound</b><br>Airport Vibra Off', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'default/vibraon2.mp3', name: '<b>notification_sound</b><br>Vibra On 120BPM', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'default/vibraoff2.mp3', name: '<b>notification_sound</b><br>Vibra Off 120 BPM', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/chorusep1-vibraon.mp3', name: '<b>notification_sound</b><br>Chorus EP 1 Vibra On', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/chorusep1-vibraoff.mp3', name: '<b>notification_sound</b><br>Chorus EP 1 Vibra Off', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/chorusep2-vibraon.mp3', name: '<b>notification_sound</b><br>Chorus EP 2 Vibra On', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/chorusep2-vibraoff.mp3', name: '<b>notification_sound</b><br>Chorus EP 2 Vibra Off', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/fm-vibraon.mp3', name: '<b>notification_sound</b><br>FM Vibra On', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/fm-vibraoff.mp3', name: '<b>notification_sound</b><br>FM Vibra Off', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/fmrode-vibraon.mp3', name: '<b>notification_sound</b><br>FM Rhode Vibra On', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/fmrode-vibraoff.mp3', name: '<b>notification_sound</b><br>FM Rhode Vibra Off', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/rhode-vibraon.mp3', name: '<b>notification_sound</b><br>Rhode Vibra On', class: 'category_announcement', loop: false, isOffensive: false },
    { file: 'vibrapack/rhode-vibraoff.mp3', name: '<b>notification_sound</b><br>Rhode Vibra Off', class: 'category_announcement', loop: false, isOffensive: false },

    { file: 'orchhit/hit-c.wav', name: '<b>bomb</b><br>OrchHit C', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-cs.wav', name: '<b>bomb</b><br>OrchHit C#', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-d.wav', name: '<b>bomb</b><br>OrchHit D', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-ds.wav', name: '<b>bomb</b><br>OrchHit D#', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-e.wav', name: '<b>bomb</b><br>OrchHit E', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-f.wav', name: '<b>bomb</b><br>OrchHit F', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-fs.wav', name: '<b>bomb</b><br>OrchHit F#', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-g.wav', name: '<b>bomb</b><br>OrchHit G', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-gs.wav', name: '<b>bomb</b><br>OrchHit G#', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-a.wav', name: '<b>bomb</b><br>OrchHit A', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-as.wav', name: '<b>bomb</b><br>OrchHit A#', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-b.wav', name: '<b>bomb</b><br>OrchHit B', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-c2.wav', name: '<b>bomb</b><br>OrchHit C2', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-cd-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>C - D</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-csds-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>C# - D#</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-de-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>D - E</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-dsf-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>D# - F</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-efs-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>E - F#</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-fg-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>F - G</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-fsgs-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>F# - G#</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-ga-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>G - A</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-gsas-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>G# - A#</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-ab-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>A - B</strong>', class: 'category_orchhit', loop: false, isOffensive: false },
    { file: 'orchhit/hit-asc-bass.wav', name: '<b>play_circle</b><br>Hit on the Time <strong>A# - C</strong>', class: 'category_orchhit', loop: false, isOffensive: false },

    { file: 'stylesavvy/check.wav', name: '<strong>Style Savvy</strong><br>Check', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/click.wav', name: '<strong>Style Savvy</strong><br>Clicked 1', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/clicked1.wav', name: '<strong>Style Savvy</strong><br>Clicked 2', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/clicked2.wav', name: '<strong>Style Savvy</strong><br>Clicked 3', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/close.wav', name: '<strong>Style Savvy</strong><br>Close', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/digitalconcern.wav', name: '<strong>Style Savvy</strong><br>Digital Concern', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/ding.wav', name: '<strong>Style Savvy</strong><br>Ding', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/error.wav', name: '<strong>Style Savvy</strong><br>Error', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/notice.wav', name: '<strong>Style Savvy</strong><br>Notice', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/oops.wav', name: '<strong>Style Savvy</strong><br>Oops!', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/ringing.wav', name: '<strong>Style Savvy</strong><br>Ringing', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/sparkling.wav', name: '<strong>Style Savvy</strong><br>Sparkling', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/sparkling2.wav', name: '<strong>Style Savvy</strong><br>Sparkling 2', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/sparkling3.wav', name: '<strong>Style Savvy</strong><br>Sparkling 3', class: 'category_und', loop: false, isOffensive: false },
    { file: 'stylesavvy/swooshlaser.wav', name: '<strong>Style Savvy</strong><br>Swoosh Laser', class: 'category_und', loop: false, isOffensive: false },

    { file: 'pokemon-sfx/FX00.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Swash', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX01.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Washed', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX02.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Beep and Sweep', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX03.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Swosh', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX04.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Swesh', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX05.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Correct 1', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX06.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Correct 2', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX07.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Transition', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX08.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Wrong', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX09.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Blop', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX0A.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Buzz', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX0B.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Dialog', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX0C.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Dialog Close', class: 'category_und', loop: false, isOffensive: false },
    { file: 'pokemon-sfx/FX0D.wav', name: '<strong>Pok&#x00E9;mon</strong><br>Open', class: 'category_und', loop: false, isOffensive: false },
];